import { Weapon, UpgradeItem, EnemyType } from './types';

export const INITIAL_WEAPONS: Weapon[] = [
  {
    id: 'plasma_laser',
    name: 'Plasma Blaster',
    type: 'laser',
    level: 1,
    maxLevel: 5,
    damage: 24,
    cooldown: 500,
    lastFired: 0,
    count: 1,
    speed: 550,
    range: 480,
    pierce: 1,
    description: 'Auto-targets nearest hostile bug with piercing energy pulses.',
    icon: 'Zap',
  },
  {
    id: 'orbital_blades',
    name: 'Orbiting Discs',
    type: 'orbit',
    level: 0,
    maxLevel: 5,
    damage: 18,
    cooldown: 0,
    lastFired: 0,
    count: 2,
    speed: 3.5, // angular velocity
    range: 85, // orbit radius
    pierce: 999,
    description: 'Rotating razor discs that shred swarming enemies in close melee.',
    icon: 'Disc',
  },
  {
    id: 'pixel_shotgun',
    name: 'Flak Scatter',
    type: 'shotgun',
    level: 0,
    maxLevel: 5,
    damage: 32,
    cooldown: 1200,
    lastFired: 0,
    count: 5,
    speed: 480,
    range: 350,
    pierce: 2,
    description: 'Fires a heavy spread of high-impact pellets with strong knockback.',
    icon: 'Crosshair',
  },
  {
    id: 'thunder_strike',
    name: 'Ion Storm',
    type: 'thunder',
    level: 0,
    maxLevel: 5,
    damage: 65,
    cooldown: 2000,
    lastFired: 0,
    count: 2,
    speed: 0,
    range: 500,
    pierce: 999,
    description: 'Calls down thunder strikes directly onto enemy clusters.',
    icon: 'CloudLightning',
  },
  {
    id: 'radiance_aura',
    name: 'Bio-Static Aura',
    type: 'aura',
    level: 0,
    maxLevel: 5,
    damage: 12,
    cooldown: 800,
    lastFired: 0,
    count: 1,
    speed: 0,
    range: 110,
    pierce: 999,
    description: 'Emits a pulsing microwave field, melting nearby small swarmers.',
    icon: 'Radio',
  },
  {
    id: 'cluster_grenade',
    name: 'Plasma Canister',
    type: 'grenade',
    level: 0,
    maxLevel: 5,
    damage: 80,
    cooldown: 2500,
    lastFired: 0,
    count: 1,
    speed: 320,
    range: 300,
    pierce: 1,
    description: 'Lobbed explosive canister creating a fiery blast on impact.',
    icon: 'Bomb',
  },
];

export const PASSIVE_UPGRADES: UpgradeItem[] = [
  {
    id: 'upgrade_damage',
    name: 'Tungsten Munitions',
    description: '+20% Damage to all weapons',
    type: 'passive',
    stat: 'damage',
    value: 0.2,
    level: 0,
    maxLevel: 5,
    icon: 'Swords',
  },
  {
    id: 'upgrade_speed',
    name: 'Servo Actuators',
    description: '+15% Player movement speed',
    type: 'passive',
    stat: 'speed',
    value: 0.15,
    level: 0,
    maxLevel: 5,
    icon: 'Wind',
  },
  {
    id: 'upgrade_cooldown',
    name: 'Overclock Module',
    description: '-12% Weapon cooldown time',
    type: 'passive',
    stat: 'cooldown',
    value: 0.12,
    level: 0,
    maxLevel: 5,
    icon: 'Clock',
  },
  {
    id: 'upgrade_magnet',
    name: 'Magnetic Coil',
    description: '+40% XP Gem collection radius',
    type: 'passive',
    stat: 'magnet',
    value: 0.4,
    level: 0,
    maxLevel: 5,
    icon: 'Magnet',
  },
  {
    id: 'upgrade_maxhp',
    name: 'Reinforced Plating',
    description: '+30 Max HP and heals 30 HP immediately',
    type: 'passive',
    stat: 'maxHp',
    value: 30,
    level: 0,
    maxLevel: 5,
    icon: 'Shield',
  },
  {
    id: 'upgrade_crit',
    name: 'Targeting Computer',
    description: '+10% Critical strike chance (2x damage)',
    type: 'passive',
    stat: 'crit',
    value: 0.1,
    level: 0,
    maxLevel: 5,
    icon: 'Target',
  },
];

export const ENEMY_CONFIGS: Record<EnemyType, {
  name: string;
  radius: number;
  speed: number;
  hp: number;
  damage: number;
  color: string;
  score: number;
  xpValue: number;
}> = {
  swarmer: {
    name: 'Drone Swarmer',
    radius: 9,
    speed: 130,
    hp: 20,
    damage: 10,
    color: '#ef4444',
    score: 10,
    xpValue: 1,
  },
  charger: {
    name: 'Chitin Charger',
    radius: 14,
    speed: 160,
    hp: 60,
    damage: 22,
    color: '#f97316',
    score: 30,
    xpValue: 3,
  },
  spitter: {
    name: 'Acid Spitter',
    radius: 12,
    speed: 95,
    hp: 45,
    damage: 16,
    color: '#a855f7',
    score: 25,
    xpValue: 2,
  },
  splitter: {
    name: 'Necro Slime',
    radius: 16,
    speed: 80,
    hp: 75,
    damage: 14,
    color: '#10b981',
    score: 40,
    xpValue: 4,
  },
  boss_goliath: {
    name: 'Mecha-Titan Goliath',
    radius: 36,
    speed: 70,
    hp: 1200,
    damage: 40,
    color: '#ec4899',
    score: 500,
    xpValue: 50,
  },
};

export const XP_PER_LEVEL = (level: number): number => {
  return Math.floor(10 + Math.pow(level, 1.6) * 12);
};
